# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ee4cae314edebfb0080c66853b2bf6e3bdb194473f48de7e6269d890536f5d75ba6d896315be9dba12c28749a66fd55cc03f341aa889d2d0d933ac2d46be09a

test:
  secret_key_base: 95d0307b387cabe39ba13d96ee79321c6eb6613a2e9043aa90e45cd2c2eca0dd37b9fa32864fcffbc8b8a09bde0fdf0d6d782c5beccde22fb73aa4ea777497ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
